"""Pure RAG V2 domain contracts for Stage 10B-1."""

from .chunking import (
    CHUNK_KEY_SCHEMA_VERSION,
    DEFAULT_CHUNK_BUDGET,
    SemanticChunker,
    chunk_key_for,
)
from .hashing import (
    build_embedding_input,
    canonical_embedding_text,
    canonical_manifest_json,
    canonical_metadata_json,
    content_hash,
    embedding_input_hash,
    manifest_hash,
    metadata_hash,
    normalize_content,
    normalize_text,
)
from .identity import (
    AttractionIdentitySource,
    handle_corpus_absence,
    merge_attraction,
    rename_attraction,
    retire_attraction,
)
from .incremental import (
    EmbeddingIdentity,
    IncrementalAction,
    IncrementalCandidate,
    IncrementalDecisionResult,
    IncrementalSubject,
    PreviousEmbedding,
    decide_incremental,
)
from .models import (
    AttractionLifecycleStatus,
    AttractionVersionMetadata,
    AttractionVersionStatus,
    ChunkStatus,
    ChunkType,
    Destination,
    DestinationLevel,
    EmbeddingInput,
    EmbeddingProfile,
    EmbeddingTask,
    ManifestAttraction,
    ManifestChunk,
    ManifestInput,
    RagV2Schema,
    SemanticChunk,
    SemanticSection,
    SourceProvenance,
    StableAttraction,
)


__all__ = [
    "RagV2Schema",
    "DestinationLevel",
    "ChunkType",
    "AttractionLifecycleStatus",
    "AttractionVersionStatus",
    "ChunkStatus",
    "EmbeddingTask",
    "Destination",
    "EmbeddingProfile",
    "SourceProvenance",
    "StableAttraction",
    "AttractionVersionMetadata",
    "SemanticSection",
    "normalize_text",
    "normalize_content",
    "content_hash",
    "canonical_metadata_json",
    "metadata_hash",
    "EmbeddingInput",
    "build_embedding_input",
    "canonical_embedding_text",
    "embedding_input_hash",
    "ManifestChunk",
    "ManifestAttraction",
    "ManifestInput",
    "canonical_manifest_json",
    "manifest_hash",
    "AttractionIdentitySource",
    "rename_attraction",
    "merge_attraction",
    "retire_attraction",
    "handle_corpus_absence",
    "SemanticChunk",
    "CHUNK_KEY_SCHEMA_VERSION",
    "DEFAULT_CHUNK_BUDGET",
    "chunk_key_for",
    "SemanticChunker",
    "IncrementalSubject",
    "IncrementalAction",
    "EmbeddingIdentity",
    "PreviousEmbedding",
    "IncrementalCandidate",
    "IncrementalDecisionResult",
    "decide_incremental",
]
