from typing import Protocol
from uuid import UUID

from app.trips.models import ConversationMessage, ShareLink, Trip


class TripRepository(Protocol):
    def create(self, trip: Trip) -> Trip: ...
    def get(self, user_id: UUID, trip_id: UUID) -> Trip | None: ...
    def list_for_user(self, user_id: UUID) -> list[Trip]: ...
    def update(self, user_id: UUID, trip_id: UUID, trip: Trip) -> Trip | None: ...
    def delete(self, user_id: UUID, trip_id: UUID) -> bool: ...
    def append_message(self, message: ConversationMessage) -> None: ...
    def create_share_link(self, share_link: ShareLink) -> ShareLink: ...
    def revoke_share_links(self, user_id: UUID, trip_id: UUID) -> None: ...
    def get_share_link(self, token_hash: str) -> ShareLink | None: ...
